networks:
  services-network:
    name: services-network

services:

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    privileged: true
    user: root
    environment:
      - POSTGRESQL_USERNAME=hackathon
      - POSTGRESQL_PASSWORD=hackathon
      - POSTGRESQL_DATABASE=hackathon
    volumes:
      - ./docker_data/postgresql:/bitnami/postgresql
    ports:
      - '5432:5432'
    networks:
      - services-network


  redis:
    image: bitnami/redis:7.2
    container_name: redis
    restart: always
    privileged: true
    user: root
    environment:
      - REDIS_PASSWORD=hackathon
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - services-network


  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    restart: always
    privileged: true
    user: root
    environment:
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin12345
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./docker_data/rabbitmq:/bitnami/rabbitmq/mnesia
    networks:
      - services-network

