networks:
  services-network:
    name: services-network

services:

  service_api:
    image: tecinforibeiro/health_solutions_architects:backend
    container_name: service_api
    privileged: true
    user: root
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_DATABASE_URL=postgresql://hackathon:hackathon@postgresql/hackathon
      - JWT_SECRET_KEY=c225eb24faae7ef623d0ff5fd98378a0
      - JWT_EXPIRATION=15
      - JWT_ALGORITHMS=HS256
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=hackathon
      - OPENAI_API_KEY=sk-proj-l3JERZWeu5Oel2MIt6WsT3BlbkFJB81s6juLJGtmywlB7z1j
      - SESSION_KEY=session
    networks:
      - services-network

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    privileged: true
    user: root
    environment:
      - POSTGRESQL_USERNAME=hackathon
      - POSTGRESQL_PASSWORD=hackathon
      - POSTGRESQL_DATABASE=hackathon
    volumes:
      - ./docker_data/postgresql:/bitnami/postgresql
    ports:
      - '5432:5432'
    networks:
      - services-network


  redis:
    image: bitnami/redis:7.2
    container_name: redis
    restart: always
    privileged: true
    user: root
    environment:
      - REDIS_PASSWORD=hackathon
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - services-network
